# General arguments
run_name: unnamed_run
debug: false

# Defaults (with their own .yaml files)
defaults:
  - flow: taylor_verlet
  - source: gaussian
  - target: trimodal
  - training: flow_matching
  
